# Generated by Django 3.0 on 2019-12-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20191211_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='resumes/', verbose_name='Upload Resume'),
        ),
    ]
