# Generated by Django 3.0 on 2019-12-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20191212_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='media/', verbose_name='Upload Resume'),
        ),
    ]
